-- ============================================================
-- SEED: Tipos, Estadisticas y Habilidades
-- ============================================================

-- TIPOS (con colores oficiales)
INSERT INTO types (name_es, name_en, color_hex) VALUES
    ('Normal',    'normal',   '#A8A878'),
    ('Fuego',     'fire',     '#F08030'),
    ('Agua',      'water',    '#6890F0'),
    ('Eléctrico', 'electric', '#F8D030'),
    ('Planta',    'grass',    '#78C850'),
    ('Hielo',     'ice',      '#98D8D8'),
    ('Lucha',     'fighting', '#C03028'),
    ('Veneno',    'poison',   '#A040A0'),
    ('Tierra',    'ground',   '#E0C068'),
    ('Volador',   'flying',   '#A890F0'),
    ('Psíquico',  'psychic',  '#F85888'),
    ('Bicho',     'bug',      '#A8B820'),
    ('Roca',      'rock',     '#B8A038'),
    ('Fantasma',  'ghost',    '#705898'),
    ('Dragón',    'dragon',   '#7038F8'),
    ('Siniestro', 'dark',     '#705848'),
    ('Acero',     'steel',    '#B8B8D0'),
    ('Hada',      'fairy',    '#EE99AC');

-- ESTADISTICAS BASE
INSERT INTO stats (name_es, name_en) VALUES
    ('PS',              'hp'),
    ('Ataque',          'attack'),
    ('Defensa',         'defense'),
    ('Ataque Especial', 'special-attack'),
    ('Defensa Especial','special-defense'),
    ('Velocidad',       'speed');

-- HABILIDADES (Gen 1 Pokemon, asignadas en Gen 3+)
INSERT INTO abilities (name_es, name_en, description_es) VALUES
    ('Espesura',         'overgrow',          'Potencia los movimientos de tipo Planta cuando los PS son bajos'),
    ('Llamarada',        'blaze',             'Potencia los movimientos de tipo Fuego cuando los PS son bajos'),
    ('Torrente',         'torrent',           'Potencia los movimientos de tipo Agua cuando los PS son bajos'),
    ('Clorofila',        'chlorophyll',       'Duplica la Velocidad bajo la luz solar'),
    ('Poder Solar',      'solar-power',       'Sube el Ataque Especial bajo la luz solar, pero reduce PS cada turno'),
    ('Lluvia Ligera',    'rain-dish',         'Recupera PS levemente en la lluvia'),
    ('Escudo Polvo',     'shield-dust',       'Bloquea los efectos secundarios de los movimientos enemigos'),
    ('Guardia Compuesta','compound-eyes',     'Aumenta la precisión del Pokemon'),
    ('Ojos de Insecto',  'tinted-lens',       'Dobla el poder de los movimientos que no son muy efectivos'),
    ('Sincronía',        'synchronize',       'Pasa al rival los estados de quemadura, parálisis o envenenamiento'),
    ('Ojo Loco',         'inner-focus',       'Evita que el Pokemon se sobresalte'),
    ('Levitación',       'levitate',          'Evita los movimientos de tipo Tierra'),
    ('Intimidación',     'intimidate',        'Baja el Ataque del rival al entrar en combate'),
    ('Carrera',          'run-away',          'Permite huir de combates salvajes sin fallo'),
    ('Flash Fuego',      'flash-fire',        'Activa el poder de los movimientos de tipo Fuego al recibir uno'),
    ('Robustez',         'sturdy',            'No puede ser derrotado de un solo golpe desde PS completos'),
    ('Tracción',         'pickup',            'Puede recoger objetos después del combate'),
    ('Ponzoña',          'poison-point',      'Puede envenenar al rival al recibir un contacto físico'),
    ('Agua Velo',        'water-veil',        'Evita que el Pokemon sea quemado'),
    ('Caparazón',        'shell-armor',       'Evita los golpes críticos'),
    ('Absorbe Agua',     'water-absorb',      'Recupera PS al recibir movimientos de tipo Agua'),
    ('Voltaabsorbe',     'volt-absorb',       'Recupera PS al recibir movimientos de tipo Eléctrico'),
    ('Paralización',     'static',            'Puede paralizar al rival al recibir un contacto físico'),
    ('Escudo Mágico',    'magic-guard',       'Solo recibe daño de ataques directos'),
    ('Sereno',           'serene-grace',      'Duplica la probabilidad de efectos adicionales'),
    ('Velocidad Natural','swift-swim',        'Duplica la Velocidad bajo la lluvia'),
    ('Adaptabilidad',    'adaptability',      'Aumenta el bonus de tipo propio a x2'),
    ('Fuerza Bruta',     'sheer-force',       'Elimina efectos adicionales para potenciar los movimientos'),
    ('Presión',          'pressure',          'Hace que los movimientos del rival gasten 2 PP en vez de 1'),
    ('Armadura',         'battle-armor',      'Evita los golpes críticos'),
    ('Tierra Firme',     'sand-veil',         'Sube la Evasión en una tormenta de arena'),
    ('Manto Marino',     'natural-cure',      'Cura los estados al retirarse del combate'),
    ('Absorbe Llamas',   'flame-body',        'Puede quemar al rival al recibir un contacto físico'),
    ('Velo Arena',       'sand-stream',       'Invoca una tormenta de arena al entrar en combate'),
    ('Visión Lince',     'keen-eye',          'Evita que bajen la Precisión del Pokemon'),
    ('Frisk',            'frisk',             'Revela el objeto del rival al entrar en combate'),
    ('Mente Sana',       'own-tempo',         'Evita que el Pokemon se confunda'),
    ('Aguante',          'sturdy',            'Sobrevive con 1 PS si es derrotado de un golpe estando lleno'),
    ('Antiflama',        'water-absorb',      'Recupera PS al recibir ataques de Agua'),
    ('Cuerpo Puro',      'immunity',          'Evita que el Pokemon sea envenenado'),
    ('Foco Interior',    'inner-focus',       'Evita retroceder ante los ataques'),
    ('Poder Oculto',     'hustle',            'Sube el Ataque pero baja la Precisión de movimientos físicos'),
    ('Multiscale',       'multiscale',        'Reduce el daño recibido a la mitad cuando los PS están llenos'),
    ('Poderoso',         'huge-power',        'Duplica el Ataque del Pokemon'),
    ('Motriz',           'motor-drive',       'Sube la Velocidad al recibir movimientos Eléctricos'),
    ('Tipo Normal',      'normalize',         'Todos los movimientos se vuelven de tipo Normal'),
    ('Rubor',            'cute-charm',        'Puede enamorar al rival de distinto género al recibir contacto físico'),
    ('Chispa',           'static',            'Puede paralizar al rival con el contacto'),
    ('Vitalidad',        'vital-spirit',      'Evita que el Pokemon se duerma'),
    ('Tanque',           'rock-head',         'Evita el daño de retroceso de movimientos como Cabezazo');
